
# COMPLEXITY DRILL (OPEATION COUNTING)

# DEVELOPING INTUITION FOR TIME/SPACE COMPLEXITY USING SIMPLE LOOP 
# STRUCTURES AND CASE ANALYSIS .

# 1. SINGLE LOOP - O(n)
# 2. NESTED LOOP - O(n^2)
# 3. TRIANGULAR LOOP - O(n^2)
# 4. HALVING LOOP - O(log(n))

