
# RECURSSIVE FACTORIAL

# BASE CASE : SIMPLEST PROBLEM THAT RETURNS ANSWER DIRECTLY
# RECURSSIVE CASE : PROBLEM SOLVED BY CALLING ITSELF WITH SMALLER INPUT
# STACK GROWTH : EACH RECURSSIVE CALL ADDS TO STACK FRAME

